; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=thumbv7k-apple-watchos %s -o - | FileCheck %s --check-prefix=CHECK --check-prefix=CHECK-V7K
; RUN: llc -mtriple=thumbv7-linux-gnueabihf %s -o - | FileCheck %s --check-prefix=CHECK --check-prefix=CHECK-AAPCS
; RUN: llc -mtriple=thumbv7-apple-ios %s -o - | FileCheck %s --check-prefix=CHECK --check-prefix=CHECK-APCS

define <32 x i8> @test_consume_arg([9 x double], <32 x i8> %vec) {
; CHECK-AAPCS-LABEL: test_consume_arg:
; CHECK-AAPCS:       @ %bb.0:
; CHECK-AAPCS-NEXT:    add r0, sp, #8
; CHECK-AAPCS-NEXT:    vld1.64 {d0, d1}, [r0]
; CHECK-AAPCS-NEXT:    add r0, sp, #24
; CHECK-AAPCS-NEXT:    vld1.64 {d2, d3}, [r0]
; CHECK-AAPCS-NEXT:    bx lr
;
; CHECK-APCS-LABEL: test_consume_arg:
; CHECK-APCS:       @ %bb.0:
; CHECK-APCS-NEXT:    add r1, sp, #76
; CHECK-APCS-NEXT:    vld1.32 {d16, d17}, [r1]
; CHECK-APCS-NEXT:    add r1, sp, #60
; CHECK-APCS-NEXT:    vld1.32 {d18, d19}, [r1]
; CHECK-APCS-NEXT:    vst1.8 {d18, d19}, [r0:128]!
; CHECK-APCS-NEXT:    vst1.64 {d16, d17}, [r0:128]
; CHECK-APCS-NEXT:    bx lr




  ret <32 x i8> %vec
}

define void @test_produce_arg() {
; CHECK-AAPCS-LABEL: test_produce_arg:
; CHECK-AAPCS:       @ %bb.0:
; CHECK-AAPCS-NEXT:    .save {r7, lr}
; CHECK-AAPCS-NEXT:    push {r7, lr}
; CHECK-AAPCS-NEXT:    .pad #40
; CHECK-AAPCS-NEXT:    sub sp, #40
; CHECK-AAPCS-NEXT:    vmov.i32 q8, #0x0
; CHECK-AAPCS-NEXT:    add r0, sp, #8
; CHECK-AAPCS-NEXT:    vst1.64 {d16, d17}, [r0]!
; CHECK-AAPCS-NEXT:    vst1.64 {d16, d17}, [r0]
; CHECK-AAPCS-NEXT:    bl test_consume_arg
; CHECK-AAPCS-NEXT:    add sp, #40
; CHECK-AAPCS-NEXT:    pop {r7, pc}
;
; CHECK-APCS-LABEL: test_produce_arg:
; CHECK-APCS:       @ %bb.0:
; CHECK-APCS-NEXT:    push {r4, r7, lr}
; CHECK-APCS-NEXT:    add r7, sp, #4
; CHECK-APCS-NEXT:    sub sp, #148
; CHECK-APCS-NEXT:    mov r4, sp
; CHECK-APCS-NEXT:    bfc r4, #0, #5
; CHECK-APCS-NEXT:    mov sp, r4
; CHECK-APCS-NEXT:    vmov r1, r2, d16
; CHECK-APCS-NEXT:    mov r0, sp
; CHECK-APCS-NEXT:    vmov.i32 q8, #0x0
; CHECK-APCS-NEXT:    str r2, [r0], #60
; CHECK-APCS-NEXT:    vst1.32 {d16, d17}, [r0]!
; CHECK-APCS-NEXT:    mov r3, r1
; CHECK-APCS-NEXT:    vst1.32 {d16, d17}, [r0]
; CHECK-APCS-NEXT:    add r0, sp, #96
; CHECK-APCS-NEXT:    bl _test_consume_arg
; CHECK-APCS-NEXT:    subs r4, r7, #4
; CHECK-APCS-NEXT:    mov sp, r4
; CHECK-APCS-NEXT:    pop {r4, r7, pc}




call <32 x i8> @test_consume_arg([9 x double] undef, <32 x i8> zeroinitializer)
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
; CHECK-V7K: {{.*}}
