; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=armv6-unknown-linux-gnu | FileCheck %s --check-prefixes=ARMV6
; RUN: llc < %s -mtriple=armv7-unknown-linux-gnu | FileCheck %s --check-prefixes=ARMV7

define { i128, i8 } @muloti_test(i128 %l, i128 %r) unnamed_addr #0 {
; ARMV6-LABEL: muloti_test:
; ARMV6:       @ %bb.0: @ %start
; ARMV6-NEXT:    push {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV6-NEXT:    sub sp, sp, #28
; ARMV6-NEXT:    ldr r10, [sp, #72]
; ARMV6-NEXT:    mov r7, r0
; ARMV6-NEXT:    str r0, [sp, #12] @ 4-byte Spill
; ARMV6-NEXT:    add lr, sp, #76
; ARMV6-NEXT:    umull r4, r0, r2, r10
; ARMV6-NEXT:    ldm lr, {r1, r5, lr}
; ARMV6-NEXT:    str r4, [r7]
; ARMV6-NEXT:    umull r4, r7, r3, r5
; ARMV6-NEXT:    umull r6, r9, lr, r2
; ARMV6-NEXT:    str r7, [sp, #4] @ 4-byte Spill
; ARMV6-NEXT:    add r4, r6, r4
; ARMV6-NEXT:    umull r7, r6, r5, r2
; ARMV6-NEXT:    ldr r5, [sp, #64]
; ARMV6-NEXT:    str r7, [sp, #16] @ 4-byte Spill
; ARMV6-NEXT:    mov r7, #0
; ARMV6-NEXT:    adds r6, r6, r4
; ARMV6-NEXT:    str r6, [sp, #8] @ 4-byte Spill
; ARMV6-NEXT:    ldr r6, [sp, #68]
; ARMV6-NEXT:    adc r7, r7, #0
; ARMV6-NEXT:    str r7, [sp, #24] @ 4-byte Spill
; ARMV6-NEXT:    umull r12, r7, r1, r5
; ARMV6-NEXT:    umull r11, r4, r6, r10
; ARMV6-NEXT:    add r12, r11, r12
; ARMV6-NEXT:    umull r11, r8, r5, r10
; ARMV6-NEXT:    mov r5, #0
; ARMV6-NEXT:    adds r12, r8, r12
; ARMV6-NEXT:    umull r2, r8, r2, r1
; ARMV6-NEXT:    adc r5, r5, #0
; ARMV6-NEXT:    str r5, [sp, #20] @ 4-byte Spill
; ARMV6-NEXT:    ldr r5, [sp, #16] @ 4-byte Reload
; ARMV6-NEXT:    adds r11, r11, r5
; ARMV6-NEXT:    ldr r5, [sp, #8] @ 4-byte Reload
; ARMV6-NEXT:    adc r5, r12, r5
; ARMV6-NEXT:    mov r12, #0
; ARMV6-NEXT:    umlal r0, r12, r3, r10
; ARMV6-NEXT:    str r5, [sp, #16] @ 4-byte Spill
; ARMV6-NEXT:    ldr r5, [sp, #12] @ 4-byte Reload
; ARMV6-NEXT:    adds r0, r2, r0
; ARMV6-NEXT:    str r0, [r5, #4]
; ARMV6-NEXT:    adcs r0, r12, r8
; ARMV6-NEXT:    mov r2, #0
; ARMV6-NEXT:    adc r12, r2, #0
; ARMV6-NEXT:    cmp r7, #0
; ARMV6-NEXT:    ldr r2, [sp, #4] @ 4-byte Reload
; ARMV6-NEXT:    movne r7, #1
; ARMV6-NEXT:    cmp r4, #0
; ARMV6-NEXT:    umlal r0, r12, r3, r1
; ARMV6-NEXT:    movne r4, #1
; ARMV6-NEXT:    cmp r2, #0
; ARMV6-NEXT:    movne r2, #1
; ARMV6-NEXT:    cmp r9, #0
; ARMV6-NEXT:    mov r10, r2
; ARMV6-NEXT:    ldr r2, [sp, #64]
; ARMV6-NEXT:    movne r9, #1
; ARMV6-NEXT:    orrs r8, r2, r6
; ARMV6-NEXT:    ldr r2, [sp, #80]
; ARMV6-NEXT:    movne r8, #1
; ARMV6-NEXT:    orrs r2, r2, lr
; ARMV6-NEXT:    movne r2, #1
; ARMV6-NEXT:    cmp r6, #0
; ARMV6-NEXT:    movne r6, #1
; ARMV6-NEXT:    cmp r1, #0
; ARMV6-NEXT:    movne r1, #1
; ARMV6-NEXT:    cmp lr, #0
; ARMV6-NEXT:    movne lr, #1
; ARMV6-NEXT:    cmp r3, #0
; ARMV6-NEXT:    movne r3, #1
; ARMV6-NEXT:    adds r0, r0, r11
; ARMV6-NEXT:    str r0, [r5, #8]
; ARMV6-NEXT:    and r1, r6, r1
; ARMV6-NEXT:    ldr r0, [sp, #16] @ 4-byte Reload
; ARMV6-NEXT:    orr r1, r1, r4
; ARMV6-NEXT:    orr r1, r1, r7
; ARMV6-NEXT:    and r2, r8, r2
; ARMV6-NEXT:    adcs r0, r12, r0
; ARMV6-NEXT:    str r0, [r5, #12]
; ARMV6-NEXT:    and r0, lr, r3
; ARMV6-NEXT:    ldr r3, [sp, #24] @ 4-byte Reload
; ARMV6-NEXT:    orr r0, r0, r9
; ARMV6-NEXT:    orr r0, r0, r10
; ARMV6-NEXT:    orr r0, r0, r3
; ARMV6-NEXT:    ldr r3, [sp, #20] @ 4-byte Reload
; ARMV6-NEXT:    orr r1, r1, r3
; ARMV6-NEXT:    orr r1, r2, r1
; ARMV6-NEXT:    orr r0, r1, r0
; ARMV6-NEXT:    mov r1, #0
; ARMV6-NEXT:    adc r1, r1, #0
; ARMV6-NEXT:    orr r0, r0, r1
; ARMV6-NEXT:    and r0, r0, #1
; ARMV6-NEXT:    strb r0, [r5, #16]
; ARMV6-NEXT:    add sp, sp, #28
; ARMV6-NEXT:    pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}
;
; ARMV7-LABEL: muloti_test:
; ARMV7:       @ %bb.0: @ %start
; ARMV7-NEXT:    push {r4, r5, r6, r7, r8, r9, r10, r11, lr}
; ARMV7-NEXT:    sub sp, sp, #44
; ARMV7-NEXT:    add lr, sp, #88
; ARMV7-NEXT:    str r0, [sp, #12] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #80]
; ARMV7-NEXT:    ldm lr, {r1, r7, lr}
; ARMV7-NEXT:    ldr r4, [sp, #84]
; ARMV7-NEXT:    umull r6, r5, r2, r1
; ARMV7-NEXT:    umull r10, r4, r4, r1
; ARMV7-NEXT:    str r6, [sp, #32] @ 4-byte Spill
; ARMV7-NEXT:    umull r6, r8, r7, r0
; ARMV7-NEXT:    umull r0, r9, r0, r1
; ARMV7-NEXT:    str r6, [sp, #40] @ 4-byte Spill
; ARMV7-NEXT:    str r0, [sp, #36] @ 4-byte Spill
; ARMV7-NEXT:    umull r6, r0, r2, r7
; ARMV7-NEXT:    str r0, [sp, #8] @ 4-byte Spill
; ARMV7-NEXT:    mov r0, #0
; ARMV7-NEXT:    umlal r5, r0, r3, r1
; ARMV7-NEXT:    str r6, [sp, #4] @ 4-byte Spill
; ARMV7-NEXT:    umull r1, r12, r3, lr
; ARMV7-NEXT:    str r1, [sp, #24] @ 4-byte Spill
; ARMV7-NEXT:    ldr r1, [sp, #100]
; ARMV7-NEXT:    umull r11, r1, r1, r2
; ARMV7-NEXT:    umull r2, r6, lr, r2
; ARMV7-NEXT:    str r11, [sp, #20] @ 4-byte Spill
; ARMV7-NEXT:    str r2, [sp, #28] @ 4-byte Spill
; ARMV7-NEXT:    ldr r2, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    str r6, [sp, #16] @ 4-byte Spill
; ARMV7-NEXT:    mov r6, #0
; ARMV7-NEXT:    add r2, r10, r2
; ARMV7-NEXT:    ldr r10, [sp, #12] @ 4-byte Reload
; ARMV7-NEXT:    adds r9, r9, r2
; ARMV7-NEXT:    adc r2, r6, #0
; ARMV7-NEXT:    str r2, [sp, #40] @ 4-byte Spill
; ARMV7-NEXT:    ldr r2, [sp, #4] @ 4-byte Reload
; ARMV7-NEXT:    adds r5, r2, r5
; ARMV7-NEXT:    ldr r2, [sp, #8] @ 4-byte Reload
; ARMV7-NEXT:    adcs r11, r0, r2
; ARMV7-NEXT:    ldr r0, [sp, #32] @ 4-byte Reload
; ARMV7-NEXT:    adc lr, r6, #0
; ARMV7-NEXT:    stm r10, {r0, r5}
; ARMV7-NEXT:    ldr r0, [sp, #24] @ 4-byte Reload
; ARMV7-NEXT:    umlal r11, lr, r3, r7
; ARMV7-NEXT:    ldr r2, [sp, #20] @ 4-byte Reload
; ARMV7-NEXT:    add r5, r2, r0
; ARMV7-NEXT:    ldr r0, [sp, #16] @ 4-byte Reload
; ARMV7-NEXT:    ldr r2, [sp, #28] @ 4-byte Reload
; ARMV7-NEXT:    adds r5, r0, r5
; ARMV7-NEXT:    ldr r0, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    adc r6, r6, #0
; ARMV7-NEXT:    adds r0, r0, r2
; ARMV7-NEXT:    str r0, [sp, #36] @ 4-byte Spill
; ARMV7-NEXT:    ldr r0, [sp, #100]
; ARMV7-NEXT:    adc r9, r9, r5
; ARMV7-NEXT:    cmp r3, #0
; ARMV7-NEXT:    movwne r3, #1
; ARMV7-NEXT:    cmp r0, #0
; ARMV7-NEXT:    mov r5, r0
; ARMV7-NEXT:    movwne r5, #1
; ARMV7-NEXT:    and r3, r5, r3
; ARMV7-NEXT:    ldr r5, [sp, #84]
; ARMV7-NEXT:    cmp r1, #0
; ARMV7-NEXT:    movwne r1, #1
; ARMV7-NEXT:    cmp r12, #0
; ARMV7-NEXT:    orr r1, r3, r1
; ARMV7-NEXT:    movwne r12, #1
; ARMV7-NEXT:    cmp r5, #0
; ARMV7-NEXT:    mov r3, r5
; ARMV7-NEXT:    movwne r3, #1
; ARMV7-NEXT:    cmp r7, #0
; ARMV7-NEXT:    movwne r7, #1
; ARMV7-NEXT:    orr r1, r1, r12
; ARMV7-NEXT:    cmp r4, #0
; ARMV7-NEXT:    and r3, r3, r7
; ARMV7-NEXT:    ldr r7, [sp, #80]
; ARMV7-NEXT:    movwne r4, #1
; ARMV7-NEXT:    cmp r8, #0
; ARMV7-NEXT:    orr r1, r1, r6
; ARMV7-NEXT:    ldr r6, [sp, #96]
; ARMV7-NEXT:    movwne r8, #1
; ARMV7-NEXT:    orrs r7, r7, r5
; ARMV7-NEXT:    orr r3, r3, r4
; ARMV7-NEXT:    movwne r7, #1
; ARMV7-NEXT:    orrs r6, r6, r0
; ARMV7-NEXT:    ldr r0, [sp, #36] @ 4-byte Reload
; ARMV7-NEXT:    movwne r6, #1
; ARMV7-NEXT:    orr r3, r3, r8
; ARMV7-NEXT:    adds r2, r11, r0
; ARMV7-NEXT:    str r2, [r10, #8]
; ARMV7-NEXT:    adcs r0, lr, r9
; ARMV7-NEXT:    str r0, [r10, #12]
; ARMV7-NEXT:    ldr r0, [sp, #40] @ 4-byte Reload
; ARMV7-NEXT:    and r2, r7, r6
; ARMV7-NEXT:    orr r0, r3, r0
; ARMV7-NEXT:    orr r0, r2, r0
; ARMV7-NEXT:    orr r0, r0, r1
; ARMV7-NEXT:    mov r1, #0
; ARMV7-NEXT:    adc r1, r1, #0
; ARMV7-NEXT:    orr r0, r0, r1
; ARMV7-NEXT:    and r0, r0, #1
; ARMV7-NEXT:    strb r0, [r10, #16]
; ARMV7-NEXT:    add sp, sp, #44
; ARMV7-NEXT:    pop {r4, r5, r6, r7, r8, r9, r10, r11, pc}
start:
  %0 = tail call { i128, i1 } @llvm.umul.with.overflow.i128(i128 %l, i128 %r) #2
  %1 = extractvalue { i128, i1 } %0, 0
  %2 = extractvalue { i128, i1 } %0, 1
  %3 = zext i1 %2 to i8
  %4 = insertvalue { i128, i8 } undef, i128 %1, 0
  %5 = insertvalue { i128, i8 } %4, i8 %3, 1
  ret { i128, i8 } %5
}

; Function Attrs: nounwind readnone speculatable
declare { i128, i1 } @llvm.umul.with.overflow.i128(i128, i128) #1

attributes #0 = { nounwind readnone uwtable }
attributes #1 = { nounwind readnone speculatable }
attributes #2 = { nounwind }
